from math import nan  # or: from numpy import nan


LABOUR_MAP = {'FLYC-300-EC-JON16-NS': {'unitsinabox': 25,
  'buildpoints': 6,
  'testonlypoints': 2,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'N10208GC-10G-ORI02': {'unitsinabox': 1,
  'buildpoints': 15,
  'testonlypoints': 7,
  'gpu': 3,
  'sop': 'Nuvo-10208GC-Outrider-Installation.pptx',
  'extra': 0.0},
 'N8108GC-QD-NM0X': {'unitsinabox': 1,
  'buildpoints': 16,
  'testonlypoints': 5,
  'gpu': 3,
  'sop': 'NoahMedical-8108GC-QD-illustration-SOP.pptx',
  'extra': 5.0},
 'N9160GC-POE-I7DC-4060-CYN02-25': {'unitsinabox': 3,
  'buildpoints': 9,
  'testonlypoints': 5,
  'gpu': 3,
  'sop': 'SF011-A-N9160GC-PoE-i7DC-4060-CYN02-25.V1.1.041224.pdf',
  'extra': 0.0},
 'NRU-110V-AGX32G-COOLIT': {'unitsinabox': 4,
  'buildpoints': 10,
  'testonlypoints': 4,
  'gpu': 0,
  'sop': 'SS001-A-NRU-110V-AGX32G-V1.1.240206.pdf',
  'extra': 0.0},
 'NRU-222S-JAO32G-UBER': {'unitsinabox': 4,
  'buildpoints': 10,
  'testonlypoints': 4,
  'gpu': 0,
  'sop': 'SF020-A-NRU-222S-Uber-V1.3.241202.pdf',
  'extra': 3.0},
 'NUVO-10003': {'unitsinabox': 1,
  'buildpoints': 12,
  'testonlypoints': 6,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-10007': {'unitsinabox': 1,
  'buildpoints': 12,
  'testonlypoints': 6,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-10108GC': {'unitsinabox': 1,
  'buildpoints': 15,
  'testonlypoints': 7,
  'gpu': 5,
  'sop': nan,
  'extra': 0.0},
 'NUVO-10108GC-10G': {'unitsinabox': 1,
  'buildpoints': 15,
  'testonlypoints': 7,
  'gpu': 5,
  'sop': nan,
  'extra': 0.0},
 'NUVO-10108GC-10G-TEST': {'unitsinabox': 1,
  'buildpoints': 15,
  'testonlypoints': 7,
  'gpu': 5,
  'sop': nan,
  'extra': 0.0},
 'NUVO-10108GC-MACHINEX': {'unitsinabox': 1,
  'buildpoints': 15,
  'testonlypoints': 7,
  'gpu': 5,
  'sop': 'SF016-A-Nuvo-10108GC-Machinex-V1.0.240723.pdf',
  'extra': 0.0},
 'NUVO-10208GC': {'unitsinabox': 1,
  'buildpoints': 15,
  'testonlypoints': 7,
  'gpu': 5,
  'sop': nan,
  'extra': 0.0},
 'NUVO-10208GC-10G': {'unitsinabox': 1,
  'buildpoints': 15,
  'testonlypoints': 7,
  'gpu': 5,
  'sop': nan,
  'extra': 0.0},
 'NUVO-2500P': {'unitsinabox': 4,
  'buildpoints': 7,
  'testonlypoints': 4,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-2510VTC': {'unitsinabox': 4,
  'buildpoints': 7,
  'testonlypoints': 4,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-2600E': {'unitsinabox': 4,
  'buildpoints': 6,
  'testonlypoints': 4,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-2600E-IGN': {'unitsinabox': 4,
  'buildpoints': 6,
  'testonlypoints': 4,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-2600E-POE': {'unitsinabox': 4,
  'buildpoints': 6,
  'testonlypoints': 4,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-2600E-POE-IGN': {'unitsinabox': 4,
  'buildpoints': 6,
  'testonlypoints': 4,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-2600J': {'unitsinabox': 4,
  'buildpoints': 6,
  'testonlypoints': 4,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-2600J-IGN': {'unitsinabox': 4,
  'buildpoints': 6,
  'testonlypoints': 4,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-2600J-POE': {'unitsinabox': 4,
  'buildpoints': 6,
  'testonlypoints': 4,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-2600J-POE-IGN': {'unitsinabox': 4,
  'buildpoints': 6,
  'testonlypoints': 4,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-2610RL-H': {'unitsinabox': 4,
  'buildpoints': 6,
  'testonlypoints': 4,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-2610VTC': {'unitsinabox': 4,
  'buildpoints': 7,
  'testonlypoints': 4,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-2611VTC': {'unitsinabox': 4,
  'buildpoints': 6,
  'testonlypoints': 4,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-2612VTC': {'unitsinabox': 4,
  'buildpoints': 6,
  'testonlypoints': 4,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-2615RL-H': {'unitsinabox': 4,
  'buildpoints': 6,
  'testonlypoints': 4,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-2700DS': {'unitsinabox': 4,
  'buildpoints': 6,
  'testonlypoints': 4,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-5002E': {'unitsinabox': 4,
  'buildpoints': 9,
  'testonlypoints': 5,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-5002LP': {'unitsinabox': 4,
  'buildpoints': 9,
  'testonlypoints': 5,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-5002P': {'unitsinabox': 4,
  'buildpoints': 9,
  'testonlypoints': 5,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-5006E': {'unitsinabox': 4,
  'buildpoints': 9,
  'testonlypoints': 5,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-5006E-POE': {'unitsinabox': 4,
  'buildpoints': 9,
  'testonlypoints': 5,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-5006LP': {'unitsinabox': 4,
  'buildpoints': 9,
  'testonlypoints': 5,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-5006LP-POE': {'unitsinabox': 4,
  'buildpoints': 9,
  'testonlypoints': 5,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-5006P': {'unitsinabox': 4,
  'buildpoints': 9,
  'testonlypoints': 5,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-5006P-POE': {'unitsinabox': 4,
  'buildpoints': 9,
  'testonlypoints': 5,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-5026E': {'unitsinabox': 1,
  'buildpoints': 9,
  'testonlypoints': 5,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-5026E-POE': {'unitsinabox': 1,
  'buildpoints': 9,
  'testonlypoints': 5,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-5095GC': {'unitsinabox': 2,
  'buildpoints': 9,
  'testonlypoints': 5,
  'gpu': 3,
  'sop': nan,
  'extra': 0.0},
 'NUVO-5095GC-POE': {'unitsinabox': 2,
  'buildpoints': 9,
  'testonlypoints': 5,
  'gpu': 3,
  'sop': nan,
  'extra': 0.0},
 'NUVO-5100VTC': {'unitsinabox': 4,
  'buildpoints': 9,
  'testonlypoints': 6,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-5104VTC': {'unitsinabox': 4,
  'buildpoints': 9,
  'testonlypoints': 6,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-5108VTC': {'unitsinabox': 4,
  'buildpoints': 9,
  'testonlypoints': 6,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-5501': {'unitsinabox': 4,
  'buildpoints': 9,
  'testonlypoints': 5,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-5501-DIO': {'unitsinabox': 4,
  'buildpoints': 9,
  'testonlypoints': 5,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-5608VR': {'unitsinabox': 1,
  'buildpoints': 9,
  'testonlypoints': 5,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-6002': {'unitsinabox': 1,
  'buildpoints': 12,
  'testonlypoints': 6,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-6032': {'unitsinabox': 1,
  'buildpoints': 12,
  'testonlypoints': 6,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-6108GC': {'unitsinabox': 1,
  'buildpoints': 12,
  'testonlypoints': 6,
  'gpu': 3,
  'sop': nan,
  'extra': 0.0},
 'NUVO-6108GC-CGN1A': {'unitsinabox': 1,
  'buildpoints': 12,
  'testonlypoints': 6,
  'gpu': 3,
  'sop': 'SF002-A-Nuvo-6108GC-i7QC-CGN1A-GTX1080-V1.0.1.211019.pdf',
  'extra': 1.0},
 'NUVO-6108GC-CGNA1': {'unitsinabox': 1,
  'buildpoints': 12,
  'testonlypoints': 6,
  'gpu': 3,
  'sop': 'SF002-A-Nuvo-6108GC-i7QC-CGN1A-GTX1080-V1.0.1.211019.pdf',
  'extra': 1.0},
 'NUVO-6108GC-IGN': {'unitsinabox': 1,
  'buildpoints': 12,
  'testonlypoints': 6,
  'gpu': 3,
  'sop': nan,
  'extra': 0.0},
 'NUVO-7002DE': {'unitsinabox': 3,
  'buildpoints': 9,
  'testonlypoints': 5,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-7002E': {'unitsinabox': 4,
  'buildpoints': 9,
  'testonlypoints': 5,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-7002LP': {'unitsinabox': 4,
  'buildpoints': 9,
  'testonlypoints': 5,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-7002LP-LME': {'unitsinabox': 4,
  'buildpoints': 9,
  'testonlypoints': 5,
  'gpu': 0,
  'sop': 'SF012-A-Nuvo-7002LP-LME-V1.1.240510.pdf',
  'extra': 0.0},
 'NUVO-7002P': {'unitsinabox': 3,
  'buildpoints': 9,
  'testonlypoints': 5,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-7006DE': {'unitsinabox': 3,
  'buildpoints': 9,
  'testonlypoints': 5,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-7006DE-POE': {'unitsinabox': 3,
  'buildpoints': 9,
  'testonlypoints': 5,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-7006E': {'unitsinabox': 4,
  'buildpoints': 9,
  'testonlypoints': 5,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-7006E-POE': {'unitsinabox': 4,
  'buildpoints': 9,
  'testonlypoints': 5,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-7006LP': {'unitsinabox': 4,
  'buildpoints': 9,
  'testonlypoints': 5,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-7006LP-MSE06': {'unitsinabox': 4,
  'buildpoints': 9,
  'testonlypoints': 5,
  'gpu': 0,
  'sop': 'SF005-A-Nuvo-7006LP-MSE06-V1.1.231220.pdf',
  'extra': 1.5},
 'NUVO-7006LP-POE': {'unitsinabox': 4,
  'buildpoints': 9,
  'testonlypoints': 5,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-7006P': {'unitsinabox': 3,
  'buildpoints': 9,
  'testonlypoints': 5,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-7006P-POE': {'unitsinabox': 3,
  'buildpoints': 9,
  'testonlypoints': 5,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-7100VTC': {'unitsinabox': 4,
  'buildpoints': 12,
  'testonlypoints': 6,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-7104VTC': {'unitsinabox': 4,
  'buildpoints': 12,
  'testonlypoints': 6,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-7108VTC': {'unitsinabox': 4,
  'buildpoints': 12,
  'testonlypoints': 6,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-7160GC': {'unitsinabox': 2,
  'buildpoints': 9,
  'testonlypoints': 5,
  'gpu': 3,
  'sop': nan,
  'extra': 0.0},
 'NUVO-7160GC-POE': {'unitsinabox': 2,
  'buildpoints': 9,
  'testonlypoints': 5,
  'gpu': 3,
  'sop': nan,
  'extra': 0.0},
 'NUVO-7162GC': {'unitsinabox': 2,
  'buildpoints': 9,
  'testonlypoints': 5,
  'gpu': 3,
  'sop': nan,
  'extra': 0.0},
 'NUVO-7162GC-POE': {'unitsinabox': 2,
  'buildpoints': 9,
  'testonlypoints': 5,
  'gpu': 3,
  'sop': nan,
  'extra': 0.0},
 'NUVO-7164GC': {'unitsinabox': 2,
  'buildpoints': 9,
  'testonlypoints': 5,
  'gpu': 3,
  'sop': nan,
  'extra': 0.0},
 'NUVO-7164GC-POE': {'unitsinabox': 2,
  'buildpoints': 9,
  'testonlypoints': 5,
  'gpu': 3,
  'sop': nan,
  'extra': 0.0},
 'NUVO-7166GC': {'unitsinabox': 2,
  'buildpoints': 9,
  'testonlypoints': 5,
  'gpu': 3,
  'sop': nan,
  'extra': 0.0},
 'NUVO-7166GC-POE': {'unitsinabox': 2,
  'buildpoints': 9,
  'testonlypoints': 5,
  'gpu': 3,
  'sop': nan,
  'extra': 0.0},
 'NUVO-7168GC': {'unitsinabox': 2,
  'buildpoints': 9,
  'testonlypoints': 5,
  'gpu': 3,
  'sop': nan,
  'extra': 0.0},
 'NUVO-7168GC-POE': {'unitsinabox': 2,
  'buildpoints': 9,
  'testonlypoints': 5,
  'gpu': 3,
  'sop': nan,
  'extra': 0.0},
 'NUVO-7200VTC': {'unitsinabox': 4,
  'buildpoints': 12,
  'testonlypoints': 6,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-7204VTC': {'unitsinabox': 4,
  'buildpoints': 12,
  'testonlypoints': 6,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-7208VTC': {'unitsinabox': 4,
  'buildpoints': 12,
  'testonlypoints': 6,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-7208VTC-DY02': {'unitsinabox': 4,
  'buildpoints': 12,
  'testonlypoints': 6,
  'gpu': 0,
  'sop': 'SS002-A-Nuvo-7208VTC-DY02-V1.0.240202.pdf',
  'extra': 0.0},
 'NUVO-7208VTC-ECOPIA': {'unitsinabox': 4,
  'buildpoints': 12,
  'testonlypoints': 6,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-7250VTC': {'unitsinabox': 4,
  'buildpoints': 12,
  'testonlypoints': 6,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-7254VTC': {'unitsinabox': 4,
  'buildpoints': 12,
  'testonlypoints': 6,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-7258VTC': {'unitsinabox': 4,
  'buildpoints': 12,
  'testonlypoints': 6,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-7501': {'unitsinabox': 4,
  'buildpoints': 9,
  'testonlypoints': 5,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-7505D': {'unitsinabox': 4,
  'buildpoints': 9,
  'testonlypoints': 5,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-7531': {'unitsinabox': 4,
  'buildpoints': 9,
  'testonlypoints': 5,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-7531-IGN': {'unitsinabox': 4,
  'buildpoints': 9,
  'testonlypoints': 5,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-8003': {'unitsinabox': 1,
  'buildpoints': 12,
  'testonlypoints': 6,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-8023': {'unitsinabox': 1,
  'buildpoints': 12,
  'testonlypoints': 6,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-8032': {'unitsinabox': 1,
  'buildpoints': 12,
  'testonlypoints': 6,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-8034': {'unitsinabox': 1,
  'buildpoints': 12,
  'testonlypoints': 6,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-8041': {'unitsinabox': 1,
  'buildpoints': 12,
  'testonlypoints': 6,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-8108GC': {'unitsinabox': 1,
  'buildpoints': 14,
  'testonlypoints': 6,
  'gpu': 3,
  'sop': nan,
  'extra': 0.0},
 'NUVO-8108GC-QD': {'unitsinabox': 1,
  'buildpoints': 14,
  'testonlypoints': 6,
  'gpu': 3,
  'sop': nan,
  'extra': 0.0},
 'NUVO-8108GC-XL': {'unitsinabox': 1,
  'buildpoints': 14,
  'testonlypoints': 6,
  'gpu': 3,
  'sop': nan,
  'extra': 0.0},
 'NUVO-8111': {'unitsinabox': 1,
  'buildpoints': 12,
  'testonlypoints': 6,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-8208GC': {'unitsinabox': 1,
  'buildpoints': 14,
  'testonlypoints': 6,
  'gpu': 3,
  'sop': nan,
  'extra': 0.0},
 'NUVO-8240GC': {'unitsinabox': 1,
  'buildpoints': 14,
  'testonlypoints': 6,
  'gpu': 3,
  'sop': nan,
  'extra': 0.0},
 'NUVO-9002DE': {'unitsinabox': 3,
  'buildpoints': 9,
  'testonlypoints': 5,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-9002E': {'unitsinabox': 3,
  'buildpoints': 9,
  'testonlypoints': 5,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-9002E-IFCN-CF1': {'unitsinabox': 3,
  'buildpoints': 9,
  'testonlypoints': 5,
  'gpu': 0,
  'sop': 'SF019-A-Nuvo-9006E-Inficon-V1.3.250127.pdf',
  'extra': 1.0},
 'NUVO-9002LP': {'unitsinabox': 3,
  'buildpoints': 9,
  'testonlypoints': 5,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-9002LP-I9IC-65W-DS-EPS03': {'unitsinabox': 3,
  'buildpoints': 9,
  'testonlypoints': 5,
  'gpu': 0,
  'sop': 'SF008-A-Nuvo-9002LP-i9IC-65W-DS-EPS03-V1.0.231120.pdf',
  'extra': 0.0},
 'NUVO-9002P': {'unitsinabox': 3,
  'buildpoints': 9,
  'testonlypoints': 5,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-9006DE': {'unitsinabox': 3,
  'buildpoints': 9,
  'testonlypoints': 5,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-9006DE-POE': {'unitsinabox': 3,
  'buildpoints': 9,
  'testonlypoints': 5,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-9006E': {'unitsinabox': 3,
  'buildpoints': 9,
  'testonlypoints': 5,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-9006E-IFCN-CF1': {'unitsinabox': 3,
  'buildpoints': 9,
  'testonlypoints': 5,
  'gpu': 0,
  'sop': 'SF019-A-Nuvo-9006E-Inficon-V1.3.250127.pdf',
  'extra': 1.0},
 'NUVO-9006E-IFCN-CF2': {'unitsinabox': 3,
  'buildpoints': 9,
  'testonlypoints': 5,
  'gpu': 0,
  'sop': 'SF022-A-Nuvo-9006E-CF2-Inficon-V1.1.250128.pdf',
  'extra': 1.5},
 'NUVO-9006E-POE': {'unitsinabox': 3,
  'buildpoints': 9,
  'testonlypoints': 5,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-9006LP': {'unitsinabox': 3,
  'buildpoints': 9,
  'testonlypoints': 5,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-9006LP-MEZ-KS-CF1-PA': {'unitsinabox': 3,
  'buildpoints': 9,
  'testonlypoints': 5,
  'gpu': 0,
  'sop': 'SF020-A-Nuvo-9006LP-MEZ-KS-CF1-PA-V1.1.241002.pdf',
  'extra': 0.0},
 'NUVO-9006LP-POE': {'unitsinabox': 3,
  'buildpoints': 9,
  'testonlypoints': 5,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-9006LP-UL-KS1': {'unitsinabox': 3,
  'buildpoints': 9,
  'testonlypoints': 5,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-9006LP-UL-KS1(EA)': {'unitsinabox': 3,
  'buildpoints': 9,
  'testonlypoints': 5,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-9006P': {'unitsinabox': 3,
  'buildpoints': 9,
  'testonlypoints': 5,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-9006P-POE': {'unitsinabox': 3,
  'buildpoints': 9,
  'testonlypoints': 5,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-9100VTC': {'unitsinabox': 4,
  'buildpoints': 14,
  'testonlypoints': 5,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-9104VTC': {'unitsinabox': 4,
  'buildpoints': 14,
  'testonlypoints': 5,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-9108VTC': {'unitsinabox': 4,
  'buildpoints': 14,
  'testonlypoints': 5,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-9160GC': {'unitsinabox': 2,
  'buildpoints': 9,
  'testonlypoints': 5,
  'gpu': 3,
  'sop': nan,
  'extra': 0.0},
 'NUVO-9160GC-POE': {'unitsinabox': 2,
  'buildpoints': 9,
  'testonlypoints': 5,
  'gpu': 3,
  'sop': nan,
  'extra': 0.0},
 'NUVO-9166GC': {'unitsinabox': 2,
  'buildpoints': 9,
  'testonlypoints': 5,
  'gpu': 3,
  'sop': nan,
  'extra': 0.0},
 'NUVO-9166GC-ORI02': {'unitsinabox': 2,
  'buildpoints': 9,
  'testonlypoints': 5,
  'gpu': 3,
  'sop': 'Nuvo-9166GC-OutRider-Installation.pptx',
  'extra': 0.0},
 'NUVO-9166GC-POE': {'unitsinabox': 2,
  'buildpoints': 9,
  'testonlypoints': 5,
  'gpu': 3,
  'sop': nan,
  'extra': 0.0},
 'NUVO-9200VTC': {'unitsinabox': 1,
  'buildpoints': 14,
  'testonlypoints': 5,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-9204VTC': {'unitsinabox': 1,
  'buildpoints': 14,
  'testonlypoints': 5,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-9208VTC': {'unitsinabox': 1,
  'buildpoints': 14,
  'testonlypoints': 5,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-9208VTC-ORI03': {'unitsinabox': 1,
  'buildpoints': 14,
  'testonlypoints': 5,
  'gpu': 0,
  'sop': 'Nuvo-9208VTC and OutRider-Installation.pptx',
  'extra': 0.0},
 'NUVO-9501': {'unitsinabox': 4,
  'buildpoints': 9,
  'testonlypoints': 5,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-9505D': {'unitsinabox': 4,
  'buildpoints': 9,
  'testonlypoints': 5,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-9531': {'unitsinabox': 4,
  'buildpoints': 9,
  'testonlypoints': 5,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-9531-FT': {'unitsinabox': 4,
  'buildpoints': 9,
  'testonlypoints': 5,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-9531-IFCN-CF1': {'unitsinabox': 4,
  'buildpoints': 9,
  'testonlypoints': 5,
  'gpu': 0,
  'sop': 'SF021-A-Nuvo-9531-Inficon-V1.2.250127.pdf',
  'extra': 1.0},
 'NUVO-9531-IGN': {'unitsinabox': 4,
  'buildpoints': 9,
  'testonlypoints': 5,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-9531-MLS': {'unitsinabox': 4,
  'buildpoints': 9,
  'testonlypoints': 5,
  'gpu': 0,
  'sop': 'customized RJ45',
  'extra': 0.0},
 'NUVO-9531-POE': {'unitsinabox': 4,
  'buildpoints': 9,
  'testonlypoints': 5,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-9531-POE-IGN': {'unitsinabox': 4,
  'buildpoints': 9,
  'testonlypoints': 5,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-9531-POE-IGN-I7DC-JS02': {'unitsinabox': 4,
  'buildpoints': 9,
  'testonlypoints': 5,
  'gpu': 0,
  'sop': 'SF010-A-Nuvo-9531-Jet01-V1.2.240208.pdf',
  'extra': 0.0},
 'NUVO-9650AWP': {'unitsinabox': 1,
  'buildpoints': 9,
  'testonlypoints': 5,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'NUVO-9650AWP-POE': {'unitsinabox': 1,
  'buildpoints': 9,
  'testonlypoints': 5,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'PB-9250-LME': {'unitsinabox': 1,
  'buildpoints': 6,
  'testonlypoints': 1,
  'gpu': 0,
  'sop': 'SF004-A-PB-9250J-SA-LME-V1.1.231010.pdf',
  'extra': 0.0},
 'POC-212': {'unitsinabox': 15,
  'buildpoints': 6,
  'testonlypoints': 3,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'POC-300': {'unitsinabox': 15,
  'buildpoints': 6,
  'testonlypoints': 3,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'POC-310': {'unitsinabox': 15,
  'buildpoints': 6,
  'testonlypoints': 3,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'POC-320': {'unitsinabox': 15,
  'buildpoints': 6,
  'testonlypoints': 3,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'POC-330': {'unitsinabox': 15,
  'buildpoints': 6,
  'testonlypoints': 3,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'POC-330-AEI01': {'unitsinabox': 15,
  'buildpoints': 6,
  'testonlypoints': 3,
  'gpu': 0,
  'sop': 'SF001-A-POC-330-AEI01-100-V1.6.240730.pdf',
  'extra': 0.0},
 'POC-351VTC': {'unitsinabox': 8,
  'buildpoints': 7,
  'testonlypoints': 3,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'POC-351VTC-70': {'unitsinabox': 8,
  'buildpoints': 7,
  'testonlypoints': 3,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'POC-351VTC-MGF02': {'unitsinabox': 8,
  'buildpoints': 7,
  'testonlypoints': 3,
  'gpu': 0,
  'sop': 'SF006-A-POC-351VTC-MGF02-V2.3.240325.pdf',
  'extra': 0.0},
 'POC-40': {'unitsinabox': 15,
  'buildpoints': 6,
  'testonlypoints': 3,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'POC-40+': {'unitsinabox': 15,
  'buildpoints': 6,
  'testonlypoints': 3,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'POC-40+IGN': {'unitsinabox': 15,
  'buildpoints': 6,
  'testonlypoints': 3,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'POC-400': {'unitsinabox': 15,
  'buildpoints': 6,
  'testonlypoints': 3,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'POC-40-DIO': {'unitsinabox': 15,
  'buildpoints': 6,
  'testonlypoints': 3,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'POC-40-IGN': {'unitsinabox': 15,
  'buildpoints': 6,
  'testonlypoints': 3,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'POC-410': {'unitsinabox': 15,
  'buildpoints': 6,
  'testonlypoints': 3,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'POC-451VTC': {'unitsinabox': 8,
  'buildpoints': 8,
  'testonlypoints': 4,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'POC-465AWP': {'unitsinabox': 8,
  'buildpoints': 8,
  'testonlypoints': 3,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'POC-515': {'unitsinabox': 8,
  'buildpoints': 6,
  'testonlypoints': 3,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'POC-515-AM2': {'unitsinabox': 8,
  'buildpoints': 6,
  'testonlypoints': 3,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'POC-545': {'unitsinabox': 8,
  'buildpoints': 6,
  'testonlypoints': 3,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'POC-551VTC': {'unitsinabox': 8,
  'buildpoints': 7,
  'testonlypoints': 3,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'POC-551VTC-ADV': {'unitsinabox': 8,
  'buildpoints': 7,
  'testonlypoints': 3,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'POC-551VTC-LME': {'unitsinabox': 8,
  'buildpoints': 7,
  'testonlypoints': 3,
  'gpu': 0,
  'sop': 'SF003-A-POC-551VTC-LME-V1.3.240320.pdf',
  'extra': 0.5},
 'POC-712': {'unitsinabox': 8,
  'buildpoints': 7,
  'testonlypoints': 3,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'POC-715': {'unitsinabox': 8,
  'buildpoints': 7,
  'testonlypoints': 3,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'POC-715-UL-EPS04': {'unitsinabox': 8,
  'buildpoints': 7,
  'testonlypoints': 3,
  'gpu': 0,
  'sop': 'SF009-A-POC-715-EPS04-V1.3.240715.pdf',
  'extra': 0.0},
 'POC-751VTC': {'unitsinabox': 8,
  'buildpoints': 8,
  'testonlypoints': 4,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'POC-764VR': {'unitsinabox': 8,
  'buildpoints': 7,
  'testonlypoints': 3,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'RGS-8805GC': {'unitsinabox': 1,
  'buildpoints': 15,
  'testonlypoints': 7,
  'gpu': 3,
  'sop': nan,
  'extra': 0.0},
 'SEMIL-1301': {'unitsinabox': 1,
  'buildpoints': 14,
  'testonlypoints': 8,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'SEMIL-1301-10G': {'unitsinabox': 1,
  'buildpoints': 14,
  'testonlypoints': 8,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'SEMIL-1311J': {'unitsinabox': 1,
  'buildpoints': 14,
  'testonlypoints': 8,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'SEMIL-1311J-10G': {'unitsinabox': 1,
  'buildpoints': 14,
  'testonlypoints': 8,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'SEMIL-1321GC': {'unitsinabox': 1,
  'buildpoints': 14,
  'testonlypoints': 8,
  'gpu': 3,
  'sop': nan,
  'extra': 0.0},
 'SEMIL-1321GC-10G-A2K': {'unitsinabox': 1,
  'buildpoints': 14,
  'testonlypoints': 8,
  'gpu': 3,
  'sop': nan,
  'extra': 0.0},
 'SEMIL-1321GC-A2K': {'unitsinabox': 1,
  'buildpoints': 14,
  'testonlypoints': 8,
  'gpu': 3,
  'sop': nan,
  'extra': 0.0},
 'SEMIL-1341GC': {'unitsinabox': 1,
  'buildpoints': 14,
  'testonlypoints': 8,
  'gpu': 3,
  'sop': nan,
  'extra': 0.0},
 'SEMIL-1341GC-10G': {'unitsinabox': 1,
  'buildpoints': 14,
  'testonlypoints': 8,
  'gpu': 3,
  'sop': nan,
  'extra': 0.0},
 'SEMIL-1704': {'unitsinabox': 1,
  'buildpoints': 14,
  'testonlypoints': 8,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'SEMIL-1704-10G': {'unitsinabox': 1,
  'buildpoints': 14,
  'testonlypoints': 8,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'SEMIL-1708': {'unitsinabox': 1,
  'buildpoints': 14,
  'testonlypoints': 8,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'SEMIL-1708-10G': {'unitsinabox': 1,
  'buildpoints': 14,
  'testonlypoints': 8,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'SEMIL-1708-I7OCG9-FF03': {'unitsinabox': 1,
  'buildpoints': 14,
  'testonlypoints': 8,
  'gpu': 0,
  'sop': 'SF018-A-SEMIL-1708-i7OCG9-FF03-Firefly-V1.0.240729.pdf',
  'extra': 0.0},
 'SEMIL-1714J': {'unitsinabox': 1,
  'buildpoints': 14,
  'testonlypoints': 8,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'SEMIL-1714J-10G': {'unitsinabox': 1,
  'buildpoints': 14,
  'testonlypoints': 8,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'SEMIL-1718J': {'unitsinabox': 1,
  'buildpoints': 14,
  'testonlypoints': 8,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'SEMIL-1718J-10G': {'unitsinabox': 1,
  'buildpoints': 14,
  'testonlypoints': 8,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'SEMIL-1724GC': {'unitsinabox': 1,
  'buildpoints': 14,
  'testonlypoints': 8,
  'gpu': 3,
  'sop': nan,
  'extra': 0.0},
 'SEMIL-1724GC-10G': {'unitsinabox': 1,
  'buildpoints': 14,
  'testonlypoints': 8,
  'gpu': 3,
  'sop': nan,
  'extra': 0.0},
 'SEMIL-1724GC-10G-A2K': {'unitsinabox': 1,
  'buildpoints': 14,
  'testonlypoints': 8,
  'gpu': 3,
  'sop': nan,
  'extra': 0.0},
 'SEMIL-1724GC-A2K': {'unitsinabox': 1,
  'buildpoints': 14,
  'testonlypoints': 8,
  'gpu': 3,
  'sop': nan,
  'extra': 0.0},
 'SEMIL-1728GC': {'unitsinabox': 1,
  'buildpoints': 14,
  'testonlypoints': 8,
  'gpu': 3,
  'sop': nan,
  'extra': 0.0},
 'SEMIL-1728GC-10G': {'unitsinabox': 1,
  'buildpoints': 14,
  'testonlypoints': 8,
  'gpu': 3,
  'sop': nan,
  'extra': 0.0},
 'SEMIL-1728GC-10G-A2K': {'unitsinabox': 1,
  'buildpoints': 14,
  'testonlypoints': 8,
  'gpu': 3,
  'sop': nan,
  'extra': 0.0},
 'SEMIL-1728GC-A2K': {'unitsinabox': 1,
  'buildpoints': 14,
  'testonlypoints': 8,
  'gpu': 3,
  'sop': nan,
  'extra': 0.0},
 'SEMIL-1744GC': {'unitsinabox': 1,
  'buildpoints': 14,
  'testonlypoints': 8,
  'gpu': 3,
  'sop': nan,
  'extra': 0.0},
 'SEMIL-1744GC-10G': {'unitsinabox': 1,
  'buildpoints': 14,
  'testonlypoints': 8,
  'gpu': 3,
  'sop': nan,
  'extra': 0.0},
 'SEMIL-1748GC': {'unitsinabox': 1,
  'buildpoints': 14,
  'testonlypoints': 8,
  'gpu': 3,
  'sop': nan,
  'extra': 0.0},
 'SEMIL-1748GC-10G': {'unitsinabox': 1,
  'buildpoints': 14,
  'testonlypoints': 8,
  'gpu': 3,
  'sop': nan,
  'extra': 0.0},
 'SEMIL-1748GC-10G-L4-EL05': {'unitsinabox': 1,
  'buildpoints': 14,
  'testonlypoints': 8,
  'gpu': 3,
  'sop': nan,
  'extra': 0.0},
 'SEMIL-1748GC-10G-L4-EL06': {'unitsinabox': 1,
  'buildpoints': 14,
  'testonlypoints': 8,
  'gpu': 3,
  'sop': nan,
  'extra': 0.0},
 'SEMIL-2007': {'unitsinabox': 1,
  'buildpoints': 14,
  'testonlypoints': 8,
  'gpu': 0,
  'sop': nan,
  'extra': 0.0},
 'SEMIL-2047GC': {'unitsinabox': 1,
  'buildpoints': 14,
  'testonlypoints': 8,
  'gpu': 3,
  'sop': nan,
  'extra': 0.0}} 


def all_part_numbers():
    return sorted(LABOUR_MAP.keys())